'''
Created on Sep 12, 2017

@author: phass
'''

RECOMMENDATION_RESCINDED = "Rescinded"
RECOMMENDATION_NONE_MADE = "None-Made"
RECOMMENDATION_NO_SIGNIFICANT_RECOMMENDATIONS = "No significant recommendations were made"
RECOMMENDATION_REC_MADE = "Made"
RECOMMENDATION_ERROR = "Error"
RECOMMENDATION_POSTED = "Posted"
RECOMMENDATION_TEXT_POSTED = "Text Rec Posted"

AUTO_NO_DOWNLOAD = "Auto No-Download"
WAIT_FOR_MORE_DATA = "Wait For Data"
DOWNLOAD = "Download"
NO_DOWNLOAD = "No Download" 