'''
Created on Oct 31, 2014

@author: rforbes
'''
CENTER = 'center'
TOP_LEFT = 'topLeft'
TOP_CENTER = 'topCenter'
TOP_RIGHT = 'topRight'
BOTTOM_LEFT = 'bottomLeft'
BOTTOM_CENTER = 'bottomCenter'
BOTTOM_RIGHT = 'bottomRight'
RIGHT = "right"
LEFT = "left"
TOP = 'top'
BOTTOM = 'bottom'

ABORTED = 'Aborted'
ACK_REQUIRED = "ackRequired"
ACK_TIME = "ackTime"
ACK_TIMED_OUT = "ackTimedOut"
BY_NAME = 'stepsByName'
CALLBACK = "callback"
CANCELED = 'canceled'
CHART_NAME = 'chartName'
CHART_PARENT = 'chart.parent'
CHART_RUN_ID = 'chartRunId'
COMMAND = "callback"
CHOICES= "choices"
CHOICES_KEY = "choicesKey"
CHOICES_RECIPE_LOCATION = "choicesRecipeLocation"
COMPUTER = 'computer'
CREATE_TIME = 'createTime'
DATA = "data"
DATABASE = "database"
DESCRIPTION = "description"
DELAY = "delay"
DELAY_UNIT = "delayUnit"
DIALOG = "dialog"
DIRECTORY = "directory"
DYNAMIC = "dynamic"
ENABLE = "enable"
EXTENSION = 'extension'
FETCH_MODE = "fetchMode"
FILEPATH = "filepath"
FILENAME = "filename"
GLOBAL = "global"
ID = 'id'
INPUT = 'input'
INSTANCE_ID = 'instanceId'
KEY = "key"
KEY_MODE = "keyMode"
LABEL = 'label'
LOCATION = 'location'
MESSAGE = "message"
MESSAGE_ID = 'messageId'
MESSAGE_QUEUE = 'messageQueue'
METHOD = "method"
MINIMUM_VALUE = "minimumValue"
MAXIMUM_VALUE = "maximumValue"
MULTIPLE = "multiple"
NAME = "name"
PAUSED = 'Paused'
POSITION = 'position'
POST_TO_QUEUE = "postToQueue"
POST_NOTIFICATION = "postNotification"
PRINT_FILE = "printFile"
PRIORITY = "priority"
PROJECT = 'project'
PROMPT = "prompt"
QUEUE = "queue"
RECIPE = "recipe"
RECIPE_LOCATION = "recipeLocation" 
RESPONSE = 'response'
RESULTS_MODE = "resultsMode" 
RUNNING = "Running"
SCALE = 'scale'
SECURITY = 'security'
SERVER = 'server'
SINGLE = "single"
SQL = "sql"
STATIC = "static"
STATUS = "status"
STOPPED = 'Stopped'
STRATEGY = "strategy"
TAG_PATH = "tagPath"
STRATEGY = "strategy"
TIMEOUT = "timeout"
TIMEOUT_UNIT = "timeoutUnit"
TIMESTAMP = "timestamp"
UPDATE = "update"
UPDATE_OR_CREATE = "updateOrCreate"
USER = 'user'
VIEW_FILE = "viewFile"
WINDOW = 'window'

MESSAGE_ID = 'messageId'
MESSAGE_QUEUE = 'messageQueue'
RECIPE_LOCATION = "recipeLocation"
LOCAL = "local"
PREVIOUS = "previous"
SUPERIOR = "superior"
NAMED = "named"
PROCEDURE = "procedure"
PHASE = "phase"
OPERATION = "operation"    

SECOND= "SECOND"
MINUTE = "MINUTE"
HOUR = "HOUR"
TIME_UNIT_TYPE = "TIME"


